
"""
Configuration and constants for AdvancedCATDAP.
"""

# Default parameters for AdvancedCATDAP
DEFAULT_USE_AICC = True
DEFAULT_MIN_CAT_FRACTION = 0.001
DEFAULT_MAX_CATEGORIES = 100
DEFAULT_TASK_TYPE = 'auto'
DEFAULT_MIN_SAMPLES_LEAF_RATE = 0.05
DEFAULT_MAX_LEAF_SAMPLES = 100
DEFAULT_NUMERIC_THRESHOLD = 0.5
DEFAULT_MAX_PAIRWISE_BINS = 50000
DEFAULT_N_INTERACTION_CANDIDATES = 100
DEFAULT_MAX_CLASSIFICATION_BYTES = 200 * 1024 * 1024  # 200 MB
DEFAULT_MAX_ESTIMATED_UNIQUES = 20000
DEFAULT_EXTRA_PENALTY = 0.0
DEFAULT_SAVE_RULES_MODE = 'top_k'
DEFAULT_VERBOSE = True

# Sklearn-style default parameters
DEFAULT_MAX_BINS = 5
DEFAULT_TOP_K = 20
DEFAULT_DELTA_THRESHOLD = 0.0

# Internal math constants
EPSILON_LOG = 1e-15
EPSILON_RSS = 1e-10
PAIR_GAIN_BASE_THRESH = 2.0
